version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      TYPE: "FORGE"
      FORGE_VERSION: "47.2.0"
      MEMORY: "12G"
      DIFFICULTY: "hard"
      ALLOW_FLIGHT: "TRUE"
      SERVER_NAME: "NAME"
      MOTD: "last update ?? ?? ????, forge 47.2"
      VIEW_DISTANCE: "10"
      SPAWN_PROTECTION: "8"
      ONLINE_MODE: 'FALSE'
      MAX_PLAYERS: "10"
      UID: 1003
      GID: 1003
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./:/data
